### ISSUE TITLE
Serif font

### ISSUE THREAD

**Issue by jennminerva** [jeremypbeasley/who-representsme#39]
I can't figure out why the serif isn't working. 

I added it to fonts.styl and I changed h1, even tried created a separate class. 

The branch is 25_jm

**Comment by jeremypbeasley** [comment]
Commented here: https://github.com/jeremypbeasley/who-representsme/pull/40

In the future, if you need help with something you've started, make a PR regardless of the shape of the code. Otherwise there's no easy way for me to see what you've changed.
