### ISSUE TITLE
update favicon

### ISSUE THREAD

**Issue by jeremypbeasley** [jeremypbeasley/who-representsme#75]
it's blue.

use a favicon generator and replace all the images and paths in the header.

**Comment by jennminerva** [comment]
I changed it from blue and used a generator to create the files. I changed the file name to match the previous file name (_favicons) and pasted the html into index. Still blue. Searched extensively on how to force refresh the favicon in local development, and I cannot figure it out. I have to be missing some step but I have no idea what it is.
